name: React CI

on:
  push:
    branches:
      - main
      - add-ci-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: my-project

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: my-project

      - name: Build React app
        run: npm run build
        working-directory: my-project
